/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;

import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JPanel;

import com.teri.systemtracking.Server.Server.CentralWorker;

/**
 *
 * @author MinhTri
 */
public class ConnectionSessionPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditUserSessionPanel
     */
    private int notifyCnt;
    private BufferedImage notifyImage;

    public ConnectionSessionPanel() {
        notifyCnt = 0;

        try {
            notifyImage = ImageIO.read(getClass().getResource("/notify-bell.png"));
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        initComponents();

        ovalButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                notifyCnt = 0;
                ovalButton1.repaint();
            }

        });

    }

    public void updateBellCntNotification() {
        notifyCnt++;
        ovalButton1.repaint();
    }

    public void addEntity(JPanel entity) {
        activeUserListPanel1.addConnectionPanel(entity);
    }

    public OvalButton getShowAllButton() {
        return activeUserListPanel1.getShowAllButton();
    }

    public void removeEntity(JPanel entity) {
        activeUserListPanel1.removeConnectionPanel(entity);
    }

    public void replaceAllInList(ArrayList<JPanel> l) {
        activeUserListPanel1.replaceAllInList(l);

    }

    public SearchBar getSearchBar() {
        return activeUserListPanel1.getSearchBar();
    }

    public JButton getNotifyButton() {
        return ovalButton1;
    }

    public static void applyQualityProperties(Graphics2D g2) {
        g2.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);
        g2.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileSelectionPanel1 = new com.teri.systemtracking.Server.GUI.FileSelectionPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        activeUserListPanel1 = new com.teri.systemtracking.Server.GUI.ActiveUserListPanel();

        setMinimumSize(new java.awt.Dimension(0, 685));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(740, 710));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 70));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Fira Code Medium", 0, 28)); // NOI18N
        jLabel1.setForeground(Color.decode("#46494c"));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connection.png"))); // NOI18N
        jLabel1.setText("Connections");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setIconTextGap(10);
        jPanel1.add(jLabel1);

        jPanel3 = new JPanel();
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 25));

        ovalButton1 = new OvalButton() {

            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);

                Graphics2D g2 = (Graphics2D) g.create();
                applyQualityProperties(g2);

                g2.drawImage(notifyImage, 2, 2, null);
                if (notifyCnt != 0) {
                    g2.setColor(Color.WHITE);
                    g2.fillOval(23, 0, 22, 22);

                    g2.setColor(Color.decode("#0582ca"));
                    g2.fillOval(25, 2, 18, 18);

                    g2.setFont(new java.awt.Font("Cascadia Code", 0, 13));
                    g2.setColor(Color.decode("#f0efeb"));
                    g2.drawString(Integer.toString(notifyCnt), 30, 16);
                }
                g2.dispose();

            }
        };
        ovalButton1.setInfo("notifications");

        ovalButton1.setPreferredSize(new Dimension(45, 45));
        jPanel3.add(ovalButton1);

        jPanel1.add(jPanel3);
        add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(300000, 300000));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        activeUserListPanel1.setMinimumSize(new java.awt.Dimension(500, 650));
        jPanel2.add(activeUserListPanel1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.teri.systemtracking.Server.GUI.ActiveUserListPanel activeUserListPanel1;
    private com.teri.systemtracking.Server.GUI.FileSelectionPanel fileSelectionPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JPanel jPanel3;
    private OvalButton ovalButton1;
    // End of variables declaration//GEN-END:variables
}
