/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author MinhTri
 */
public class DateRegistryPanel extends javax.swing.JPanel {

    /**
     * Creates new form DateRegistryPanel
     */
    public DateRegistryPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(0x8e, 0xca, 0xe6, 100));
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 8, 8);
        g2.dispose();
        super.paintComponent(g);
    }
    
    public void setDate(Date date) {
        SimpleDateFormat localDateFormat = new SimpleDateFormat("HH:mm:ss");
        String time = localDateFormat.format(date);
        this.time.setText(time);
        this.date.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10),
                new java.awt.Dimension(10, 10));
        date = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10),
                new java.awt.Dimension(10, 10));
        time = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(160, 30));
        setMinimumSize(new java.awt.Dimension(160, 30));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(160, 30));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler1);

        date.setFont(new java.awt.Font("Fira Code Medium", 0, 12)); // NOI18N
        date.setForeground(new java.awt.Color(0x00, 0x77, 0xb6));
        date.setText("17/12/2023");
        add(date);
        add(filler2);

        time.setFont(new java.awt.Font("Fira Code Medium", 0, 12)); // NOI18N
        time.setForeground(new java.awt.Color(0x00, 0x77, 0xb6));
        time.setText("00:00:00");
        time.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(time);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
