/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.teri.systemtracking.Server.Server.CentralWorker;

/**
 *
 * @author MinhTri
 */
public class EditUserSessionPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditUserSessionPanel
     */
    public EditUserSessionPanel() {
        initComponents();
        ovalButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                HelpPanel.showHelp();
            }

        });
    }

    public void setShowPanel(String s) {
        ((CardLayout) jPanel2.getLayout()).show(jPanel2, s);
    }

    public ObservedActionListPanel getObservedListPanel() {
        return observedActionListPanel1;
    }

    public FileSelectionPanel getFileSelectonPanel() {
        return fileSelectionPanel1;
    }

    public void setEntityProperty(int id) {
        jLabel1.setText("Client#" + Integer.toString(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fileSelectionPanel1 = new com.teri.systemtracking.Server.GUI.FileSelectionPanel();
        observedActionListPanel1 = new com.teri.systemtracking.Server.GUI.ObservedActionListPanel();

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 50));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Fira Code Medium", 0, 28)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jLabel1.setText("Client#abcd134");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setForeground(Color.decode("#46494c"));
        jLabel1.setIconTextGap(10);
        jPanel1.add(jLabel1);

        jPanel3 = new javax.swing.JPanel();
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));
        ovalButton1 = new OvalButton();
        ovalButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/question-mark.png"))); // NOI18N
        ovalButton1.setInfo("help");
        ovalButton1.setMaximumSize(new java.awt.Dimension(35, 35));
        ovalButton1.setMinimumSize(new java.awt.Dimension(35, 35));
        ovalButton1.setPreferredSize(new java.awt.Dimension(35, 35));
        jPanel3.add(ovalButton1);

        jPanel1.add(jPanel3);

        add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(fileSelectionPanel1, "file selection");
        jPanel2.add(observedActionListPanel1, "observed events");

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.teri.systemtracking.Server.GUI.FileSelectionPanel fileSelectionPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private OvalButton ovalButton1;
    private com.teri.systemtracking.Server.GUI.ObservedActionListPanel observedActionListPanel1;
    // End of variables declaration//GEN-END:variables
}
