/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import com.teri.systemtracking.Server.presenter.FileSelectionPresenter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author MinhTri
 */
public class FileSelectionPanel extends javax.swing.JPanel {

      private FileSelectionPresenter presenter;

      public FileSelectionPanel() {
            initComponents();
            listScrollPane.updateContentComponent(listFilePanel);
            initActions();
      }

      private void initActions() {

            trackFileButton.addActionListener(new ActionListener() {
                  @Override
                  public void actionPerformed(ActionEvent e) {
                        if (presenter != null) {
                              presenter.trackSelectedFile();
                        }
                  }
            });
            backButton.addActionListener(new ActionListener() {
                  @Override
                  public void actionPerformed(ActionEvent e) {

                        if (presenter != null)
                              presenter.navigateBack();
                  }
            });
      }

      public void setPresenter(FileSelectionPresenter presenter) {
            this.presenter = presenter;
      }

      public JPanel getListFilePanel() {
            return listFilePanel;
      }

      public FileSearchBar getSearchBar() {
            return searchBar;
      }

      public JPanel getDrivePanel() {
            return drivePannel;
      }

      public void setEnteredFolder(String folder) {
            this.folderLabel.setText(folder);
      }

      /**
       * This method is called from within the constructor to initialize the form.
       * WARNING: Do NOT modify this code. The content of this method is always
       * regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            listFilePanel = new javax.swing.JPanel();
            jPanel9 = new javax.swing.JPanel();
            jPanel10 = new javax.swing.JPanel();
            filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(10, 20),
                  new java.awt.Dimension(10, 20));
            jLabel1 = new javax.swing.JLabel();
            searchBar = new com.teri.systemtracking.Server.GUI.FileSearchBar();
            filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10),
                  new java.awt.Dimension(10, 10));
            drivePannel = new javax.swing.JPanel();
            jPanel8 = new javax.swing.JPanel();
            jPanel3 = new javax.swing.JPanel();
            jPanel6 = new javax.swing.JPanel();
            backButton = new com.teri.systemtracking.Server.GUI.OvalButton();
            jLabel2 = new javax.swing.JLabel();
            jPanel7 = new javax.swing.JPanel();
            folderLabel = new javax.swing.JLabel();
            trackFileButton = new com.teri.systemtracking.Server.GUI.OvalButton();
            contentJPanel = new javax.swing.JPanel();
            jPanel5 = new javax.swing.JPanel();
            filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 10), new java.awt.Dimension(20, 10),
                  new java.awt.Dimension(20, 10));
            jLabel4 = new javax.swing.JLabel();
            filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 10), new java.awt.Dimension(225, 10),
                  new java.awt.Dimension(235, 10));
            listScrollPane = new com.teri.systemtracking.Server.GUI.ListScrollPane();
            filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 30), new java.awt.Dimension(20, 30),
                  new java.awt.Dimension(20, 30));
            filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 15), new java.awt.Dimension(20, 15),
                  new java.awt.Dimension(20, 15));

            listFilePanel.setOpaque(false);
            listFilePanel.setLayout(new javax.swing.BoxLayout(listFilePanel, javax.swing.BoxLayout.Y_AXIS));

            setOpaque(false);
            setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

            jPanel9.setMaximumSize(new java.awt.Dimension(300, 32767));
            jPanel9.setMinimumSize(new java.awt.Dimension(300, 32));
            jPanel9.setOpaque(false);
            jPanel9.setPreferredSize(new java.awt.Dimension(300, 100));
            jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

            jPanel10.setMaximumSize(new java.awt.Dimension(3000, 50));
            jPanel10.setOpaque(false);
            jPanel10.setPreferredSize(new java.awt.Dimension(100, 60));
            jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));
            jPanel10.add(filler4);

            jLabel1.setFont(new java.awt.Font("Fira Code Medium", 0, 24)); // NOI18N
            jLabel1.setText("Storage");
            jLabel1.setAlignmentY(0.7F);
            jLabel1.setForeground(Color.decode("#46494c"));
            jLabel2.setForeground(Color.decode("#46494c"));
            jLabel4.setForeground(Color.decode("#46494c"));

            jPanel10.add(jLabel1);
            jPanel10.setAlignmentX(0.5f);

            jPanel9.add(jPanel10);

            searchBar.setFontSize(14);
            searchBar.setMaximumSize(new java.awt.Dimension(280, 40));
            searchBar.setMinimumSize(new java.awt.Dimension(280, 40));
            searchBar.setPreferredSize(new java.awt.Dimension(280, 40));
            searchBar.setText("search by path");
            searchBar.setAlignmentX(0.5f);

            jPanel9.add(searchBar);

            filler1.setAlignmentX(0.0F);
            jPanel9.add(filler1);

            drivePannel.setMaximumSize(new java.awt.Dimension(30000, 30000));
            drivePannel.setMinimumSize(new java.awt.Dimension(250, 0));
            drivePannel.setOpaque(false);
            drivePannel.setPreferredSize(new java.awt.Dimension(250, 100));
            drivePannel.setLayout(new javax.swing.BoxLayout(drivePannel, javax.swing.BoxLayout.Y_AXIS));
            drivePannel.setAlignmentX(0.5f);
            jPanel9.add(drivePannel);

            add(jPanel9);

            jPanel8.setOpaque(false);
            jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

            jPanel3.setAlignmentX(0.0F);
            jPanel3.setMaximumSize(new java.awt.Dimension(1060, 30000));
            jPanel3.setOpaque(false);
            jPanel3.setPreferredSize(new java.awt.Dimension(1060, 700));
            jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

            jPanel6.setAlignmentX(0.0F);
            jPanel6.setMaximumSize(new java.awt.Dimension(32767, 40));
            jPanel6.setMinimumSize(new java.awt.Dimension(186, 40));
            jPanel6.setOpaque(false);
            jPanel6.setPreferredSize(new java.awt.Dimension(100, 40));
            jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

            backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous.png"))); // NOI18N
            backButton.setInfo("back");
            backButton.setMaximumSize(new java.awt.Dimension(30, 30));
            backButton.setMinimumSize(new java.awt.Dimension(30, 30));
            backButton.setPreferredSize(new java.awt.Dimension(30, 30));
            jPanel6.add(backButton);

            jLabel2.setFont(new java.awt.Font("Fira Code Medium", 0, 22)); // NOI18N
            jLabel2.setText("My Files");
            jLabel2.setMaximumSize(new java.awt.Dimension(200, 60));
            jLabel2.setMinimumSize(new java.awt.Dimension(200, 50));
            jLabel2.setPreferredSize(new java.awt.Dimension(200, 50));
            jPanel6.add(jLabel2);

            jPanel7.setOpaque(false);
            jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));

            folderLabel.setFont(new java.awt.Font("Segoe UI Variable", 2, 16)); // NOI18N
            folderLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            folderLabel.setText("selected folder");
            folderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            folderLabel.setMaximumSize(new java.awt.Dimension(24, 25));
            folderLabel.setMinimumSize(new java.awt.Dimension(24, 25));
            folderLabel.setPreferredSize(new java.awt.Dimension(400, 25));
            jPanel7.add(folderLabel);

            trackFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
            trackFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            trackFileButton.setInfo("track selected file");
            trackFileButton.setMaximumSize(new java.awt.Dimension(40, 40));
            trackFileButton.setMinimumSize(new java.awt.Dimension(40, 40));
            trackFileButton.setPreferredSize(new java.awt.Dimension(40, 40));
            jPanel7.add(trackFileButton);

            jPanel6.add(jPanel7);

            jPanel3.add(jPanel6);

            contentJPanel.setMaximumSize(new java.awt.Dimension(300000, 30000));
            contentJPanel.setOpaque(false);
            contentJPanel.setLayout(new javax.swing.BoxLayout(contentJPanel, javax.swing.BoxLayout.Y_AXIS));

            jPanel5.setAlignmentX(0.0F);
            jPanel5.setMaximumSize(new java.awt.Dimension(32767, 35));
            jPanel5.setMinimumSize(new java.awt.Dimension(294, 35));
            jPanel5.setOpaque(false);
            jPanel5.setPreferredSize(new java.awt.Dimension(100, 35));
            jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
            jPanel5.add(filler5);

            jLabel4.setFont(new java.awt.Font("Fira Code Medium", 0, 16)); // NOI18N
            jLabel4.setText("filename");
            jPanel5.add(jLabel4);
            jPanel5.add(filler2);

            contentJPanel.add(jPanel5);

            listScrollPane.setBorder(null);
            listScrollPane.setAlignmentX(0.0F);
            listScrollPane.setOpaque(false);
            contentJPanel.add(listScrollPane);

            filler8.setAlignmentX(0.0F);
            contentJPanel.add(filler8);

            jPanel3.add(contentJPanel);

            jPanel8.add(jPanel3);

            filler9.setAlignmentX(0.0F);
            jPanel8.add(filler9);

            add(jPanel8);
      }// </editor-fold>//GEN-END:initComponents

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private com.teri.systemtracking.Server.GUI.OvalButton backButton;
      private javax.swing.JPanel contentJPanel;
      private javax.swing.Box.Filler filler1;
      private javax.swing.Box.Filler filler2;
      private javax.swing.Box.Filler filler4;
      private javax.swing.Box.Filler filler5;
      private javax.swing.Box.Filler filler8;
      private javax.swing.Box.Filler filler9;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel folderLabel;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JPanel jPanel10;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JPanel drivePannel;
      private javax.swing.JPanel jPanel5;
      private javax.swing.JPanel jPanel6;
      private javax.swing.JPanel jPanel7;
      private javax.swing.JPanel jPanel8;
      private javax.swing.JPanel jPanel9;
      private javax.swing.JPanel listFilePanel;
      private com.teri.systemtracking.Server.GUI.ListScrollPane listScrollPane;
      private com.teri.systemtracking.Server.GUI.FileSearchBar searchBar;
      private com.teri.systemtracking.Server.GUI.OvalButton trackFileButton;
      // End of variables declaration//GEN-END:variables
}
