/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import com.teri.systemtracking.Server.presenter.FilePresenter;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @author MinhTri
 */
public class FilePanel extends javax.swing.JPanel {

      private FilePresenter presenter;
      private Color color;

      public static final Color normal = new Color(0, 0, 0, 0);
      public static final Color enter = new Color(0, 0, 0, 15);
      public static final Color press = new Color(0, 0, 0, 25);
      public static final Color selected = new Color(0, 0, 0, 25);

      public FilePanel() {
            initComponents();
            color = normal;
            initActions();
      }

      private void initActions() {
            addMouseListener(new MouseAdapter() {
                  @Override
                  public void mouseEntered(MouseEvent e) {
                        if (color != selected) {
                              color = enter;
                              repaint();
                        }
                  }

                  @Override
                  public void mouseExited(MouseEvent e) {
                        if (color != selected) {
                              color = normal;
                              repaint();
                        }
                  }

                  @Override
                  public void mousePressed(MouseEvent e) {
                        if (color != selected) {
                              color = press;
                              repaint();
                        }
                  }

                  @Override
                  public void mouseReleased(MouseEvent e) {
                        if (color != selected) {
                              color = enter;
                              repaint();
                        }
                  }
            });
            addMouseListener(new MouseAdapter() {
                  @Override
                  public void mouseClicked(MouseEvent e) {
                        requestFocusInWindow();
                        if (presenter != null) {
                              presenter.onClicked();
                              if (e.getClickCount() == 2) {
                                    presenter.onDoubleClicked();
                              }
                        }
                  }
            });
      }

      public void setPresenter(FilePresenter presenter) {
            this.presenter = presenter;
      }

      public void initView(String name) {
            filename.setText(name);
      }

      public void setSelected(boolean s) {
            if (s) {
                  color = selected;
            } else {
                  color = normal;
            }
            repaint();
      }

      @Override
      public void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                  RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(enter);
            g2.fillRect(0, getHeight() - 1, getWidth(), 1);
            g2.setColor(color);
            g2.fillRoundRect(1, 0, getWidth() - 1, getHeight() - 1, 5, 5);
            g2.dispose();
            super.paintComponent(g);
      }

      /**
       * This method is called from within the constructor to initialize the form.
       * WARNING: Do NOT modify this code. The content of this method is always
       * regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 10), new java.awt.Dimension(20, 10),
                  new java.awt.Dimension(20, 10));
            jLabel1 = new javax.swing.JLabel();
            filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 10), new java.awt.Dimension(10, 10),
                  new java.awt.Dimension(10, 10));
            filename = new javax.swing.JLabel();

            setMaximumSize(new java.awt.Dimension(840, 43));
            setOpaque(false);
            setPreferredSize(new java.awt.Dimension(840, 43));
            setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
            add(filler4);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
            add(jLabel1);
            add(filler3);

            filename.setFont(new java.awt.Font("Segoe UI Variable", 0, 16)); // NOI18N
            filename.setText("filename");
            add(filename);
      }// </editor-fold>//GEN-END:initComponents

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.Box.Filler filler3;
      private javax.swing.Box.Filler filler4;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel filename;
      // End of variables declaration//GEN-END:variables
}
