/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import com.teri.systemtracking.Server.ClientWorker.Client;

/**
 *
 * @author MinhTri
 */
public class FileEntityPanel extends javax.swing.JPanel {

    /**
     * Creates new form FileEntityPanel
     */
    private Color cl;
    private Color normal;
    private Color enter;
    private Color press;
    private Color selected;

    public FileEntityPanel() {
        initComponents();
        normal = new Color(0, 0, 0, 0);
        enter = new Color(0, 0, 0, 15);
        press = new Color(0, 0, 0, 25);
        selected = new Color(0, 0, 0, 25);
        cl = normal;
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (cl != selected) {
                    cl = enter;
                    repaint();
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (cl != selected) {
                    cl = normal;
                    repaint();
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if (cl != selected) {
                    cl = press;
                    repaint();
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (cl != selected) {
                    cl = enter;
                    repaint();
                }
            }
        });
    }

    private void setCommands(final Client client, final String path) {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    client.setSelectedPath(path, FileEntityPanel.this);
                    requestFocusInWindow();
                    if (e.getClickCount() == 2) {
                        client.getListFile(path);
                    }
                } catch (InterruptedException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            }
        });
    }

    public void setProperty(String path, String name, final Client client) {
        setCommands(client, path);
        jLabel3.setText(name);
    }

    public void setSelected(boolean s) {
        if (s) {
            cl = selected;
        } else {
            cl = normal;
        }
        repaint();

    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(enter);
        g2.fillRect(0, getHeight() - 1, getWidth(), 1);
        g2.setColor(cl);
        g2.fillRoundRect(1, 0, getWidth() - 1, getHeight() - 1, 5, 5);
        g2.dispose();
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 10), new java.awt.Dimension(20, 10),
                new java.awt.Dimension(20, 10));
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 10), new java.awt.Dimension(10, 10),
                new java.awt.Dimension(10, 10));
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(840, 43));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(840, 43));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler4);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
        add(jLabel1);
        add(filler3);

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 16)); // NOI18N
        jLabel3.setText("filename");
        add(jLabel3);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
