/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

/**
 * @author MinhTri
 */
public class MainFrame extends javax.swing.JFrame {

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private ContentPanel contentPanel2;

      /**
       * Creates new form MainFrame
       */
      public MainFrame() {
            initComponents();
            // this.getContentPane().add(contentPanePanel1, BorderLayout.CENTER);
            this.pack();
            // this.addComponentListener(new ComponentListener() {
            // @Override
            // public void componentResized(ComponentEvent e) {
            // }

            // @Override
            // public void componentMoved(ComponentEvent e) {
            // PopupWindow.getInfoPopup().updateLocation();
            // PopupWindow.getSearchPopup().updateLocation();
            // }
            // @Override
            // public void componentShown(ComponentEvent e) {
            // }
            // @Override
            // public void componentHidden(ComponentEvent e) {
            // if (PopupWindow.getInfoPopup().isVisible()) {
            // PopupWindow.getInfoPopup().setVisible(false);
            // }
            // if (PopupWindow.getSearchPopup().isVisible()) {
            // PopupWindow.getSearchPopup().setVisible(false);
            // }
            // }
            // });
            setLocationRelativeTo(null);
      }

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
            // (optional) ">
            /*
             * If Nimbus (introduced in Java SE 6) is not available, stay with the default
             * look and feel.
             * For details see
             * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        }

                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            // </editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new MainFrame().setVisible(true);
                  }
            });
      }

      public ContentPanel getContentPanePanel() {
            return contentPanel2;
      }

      /**
       * This method is called from within the constructor to initialize the form.
       * WARNING: Do NOT modify this code. The content of this method is always
       * regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            contentPanel2 = new ContentPanel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            contentPanel2.setPreferredSize(new java.awt.Dimension(1130, 810));
            getContentPane().add(contentPanel2, java.awt.BorderLayout.CENTER);
      }// </editor-fold>//GEN-END:initComponents
      // End of variables declaration//GEN-END:variables
}
