/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.Date;

import javax.swing.JFileChooser;

import com.jhlabs.image.GaussianFilter;
import com.teri.systemtracking.Server.ClientWorker.Client;

/**
 *
 * @author MinhTri
 */
public class ObservedActionEntityPanel extends javax.swing.JPanel {

    /**
     * Creates new form ActiveUserEntityPanel
     */
    private BufferedImage vcl;

    public ObservedActionEntityPanel() {
        initComponents();
        BufferedImage mask = new BufferedImage(
                (int) getPreferredSize().getWidth(), (int) getPreferredSize().getHeight(), BufferedImage.TYPE_INT_ARGB);

        Graphics2D m = mask.createGraphics();
        applyQualityProperties(m);

        m.setColor(Color.BLACK);
        m.fillRoundRect(10, 10,
                (int) getPreferredSize().getWidth() - 20, (int) getPreferredSize().getHeight() - 20, 15, 15);

        m.dispose();

        vcl = new BufferedImage((int) getPreferredSize().getWidth(),
                (int) getPreferredSize().getHeight(), BufferedImage.TYPE_INT_ARGB);

        Graphics2D cc = vcl.createGraphics();
        applyQualityProperties(cc);

        cc.drawImage(mask, 0, 0, null);

        cc.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_IN, 0.05f));

        cc.setColor(Color.BLACK);
        cc.fillRoundRect(10, 10,
                (int) getPreferredSize().getWidth() - 20, (int) getPreferredSize().getHeight() - 20, 15, 15);
        cc.dispose();

        GaussianFilter gg = new GaussianFilter(10);
        vcl = gg.filter(vcl, null);
        vcl = gg.filter(vcl, null);
        vcl = gg.filter(vcl, null);
    }

    public void setProperty(String path, String effect, Date date, final Client client) {
        fileName.setText(effect);
        this.date.setDate(date);
        filePath.setText(path);
    }

    public static void applyQualityProperties(Graphics2D g2) {
        g2.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);
        g2.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        applyQualityProperties(g2);

        g2.drawImage(vcl, 0, 0, null);

        g2.setColor(Color.WHITE);
        g2.fillRoundRect(10, 10, getWidth() - 20, getHeight() - 20, 15, 15);
        g2.dispose();
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 10), new java.awt.Dimension(25, 10),
                new java.awt.Dimension(25, 10));
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25),
                new java.awt.Dimension(25, 25));
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 25),
                new java.awt.Dimension(5, 25));
        fileName = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25),
                new java.awt.Dimension(25, 25));
        jPanel2 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25),
                new java.awt.Dimension(25, 25));
        date = new com.teri.systemtracking.Server.GUI.DateRegistryPanel();
        jPanel3 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25),
                new java.awt.Dimension(25, 25));
        filePath = new javax.swing.JTextArea();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25),
                new java.awt.Dimension(25, 25));

        setAlignmentX(0.0F);
        setMaximumSize(new java.awt.Dimension(250, 230));
        setMinimumSize(new java.awt.Dimension(250, 230));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(250, 230));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        filler9.setAlignmentX(0.0F);
        add(filler9);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(285, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(285, 60));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(285, 60));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        filler1.setAlignmentX(0.0F);
        jPanel1.add(filler1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event.png"))); // NOI18N
        jPanel1.add(jLabel1);

        filler2.setAlignmentX(0.0F);
        jPanel1.add(filler2);

        fileName.setFont(new java.awt.Font("Fira Code Medium", 0, 17)); // NOI18N
        fileName.setText("FILE#Name");
        fileName.setToolTipText("");
        fileName.setMaximumSize(new java.awt.Dimension(30000, 40));
        fileName.setMinimumSize(new java.awt.Dimension(0, 40));
        fileName.setPreferredSize(new java.awt.Dimension(182, 40));
        jPanel1.add(fileName);

        filler8.setAlignmentX(0.0F);
        jPanel1.add(filler8);

        add(jPanel1);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setMaximumSize(new java.awt.Dimension(285, 45));
        jPanel2.setMinimumSize(new java.awt.Dimension(285, 40));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(285, 40));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        filler3.setAlignmentX(0.0F);
        jPanel2.add(filler3);
        jPanel2.add(date);

        add(jPanel2);

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(285, 95));
        jPanel3.setMinimumSize(new java.awt.Dimension(285, 40));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(285, 40));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        filler5.setAlignmentX(0.0F);
        jPanel3.add(filler5);

        filePath.setEditable(false);
        filePath.setColumns(20);
        filePath.setFont(new java.awt.Font("Segoe UI Variable", 0, 16)); // NOI18N
        filePath.setLineWrap(true);
        filePath.setRows(5);
        filePath.setWrapStyleWord(true);
        filePath.setBorder(null);
        filePath.setMinimumSize(new java.awt.Dimension(0, 22));
        filePath.setOpaque(false);
        jPanel3.add(filePath);

        filler7.setAlignmentX(0.0F);
        jPanel3.add(filler7);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.teri.systemtracking.Server.GUI.DateRegistryPanel date;
    private javax.swing.JLabel fileName;
    private javax.swing.JTextArea filePath;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
