/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teri.systemtracking.Server.GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import com.teri.systemtracking.Server.ClientWorker.Client;

/**
 *
 * @author MinhTri
 */
public class SearchEntityPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchEntityPanel
     */
    private Color cl;
    private Color normal;
    private Color enter;
    private Color press;

    public SearchEntityPanel() {
        initComponents();
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        normal = new Color(0, 0, 0, 0);
        enter = new Color(0, 0, 0, 15);
        press = new Color(0, 0, 0, 30);
        cl = normal;
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                cl = enter;
                repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                cl = normal;
                repaint();
            }

            @Override
            public void mousePressed(MouseEvent e) {
                cl = press;
                repaint();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                cl = enter;
                repaint();
            }
        });
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(cl);
        g2.fillRect(1, 0, getWidth() - 1, getHeight());
        g2.dispose();
        super.paintComponent(g);
    }

    public void setContent(final String content) {
        jLabel1.setText(content);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 50), new java.awt.Dimension(30, 50),
                new java.awt.Dimension(20, 50));
        jLabel1 = new javax.swing.JLabel();

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(30000, 30));
        setMinimumSize(new java.awt.Dimension(86, 30));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 30));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel1.setText("content");
        jLabel1.setFocusable(false);
        jLabel1.setRequestFocusEnabled(false);
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
