/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.teri.systemtracking.Client.GUI;

import com.teri.systemtracking.Client.socketclient.Client;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

public class MainFrame extends javax.swing.JFrame {

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private com.teri.systemtracking.Client.GUI.RoundedButton connectButton;
      private javax.swing.Box.Filler filler1;
      private javax.swing.Box.Filler filler2;
      private javax.swing.Box.Filler filler4;
      private javax.swing.JLabel status;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private com.teri.systemtracking.Client.GUI.SearchBar searchBar;

      /**
       * Creates new form MainFrame
       */
      public MainFrame(Client client) {
            initComponents();
            setLocationRelativeTo(null);
            connectButton.addActionListener(new ActionListener() {

                  @Override
                  public void actionPerformed(ActionEvent e) {
                        try {
                              client.start(searchBar.getTextField().getText(), 6969);
                              status.setText("connected");
                              searchBar.getTextField().setEditable(false);
                              connectButton.setEnabled(false);

                        } catch (IOException e1) {
                              status.setText("failed");
                        }
                  }
            });
      }

      /**
       * This method is called from within the constructor to initialize the form.
       * WARNING: Do NOT modify this code. The content of this method is always
       * regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // <editor-fold defaultstate="collapsed" desc="Generated
      // Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new JPanel() {
                  @Override
                  public void paintComponent(Graphics g) {
                        Graphics2D g2 = (Graphics2D) g.create();
                        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                              RenderingHints.VALUE_ANTIALIAS_ON);
                        g2.setColor(Color.WHITE);
                        g2.fillRect(0, 0, getWidth(), getHeight());
                        g2.dispose();
                        super.paintComponent(g);
                  }

            };
            jPanel2 = new JPanel() {
                  @Override
                  public void paintComponent(Graphics g) {
                        Graphics2D g2 = (Graphics2D) g.create();
                        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                              RenderingHints.VALUE_ANTIALIAS_ON);
                        g2.setColor(new Color(0, 0, 0, 30));
                        g2.fillRect(0, 0, getWidth(), getHeight());
                        g2.dispose();
                        super.paintComponent(g);
                  }

            };
            filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25),
                  new java.awt.Dimension(25, 25));
            status = new javax.swing.JLabel();
            filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 10),
                  new java.awt.Dimension(25, 10));
            searchBar = new com.teri.systemtracking.Client.GUI.SearchBar();
            filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 10),
                  new java.awt.Dimension(25, 10));
            connectButton = new com.teri.systemtracking.Client.GUI.RoundedButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setOpaque(false);
            jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

            jPanel2.setAlignmentX(0.0F);
            jPanel2.setAlignmentY(0.0F);
            jPanel2.setMaximumSize(new java.awt.Dimension(30000, 30000));
            jPanel2.setOpaque(false);
            jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
            jPanel2.add(filler2);

            status.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
            status.setText("status");
            status.setAlignmentX(0.5F);
            jPanel2.add(status);
            jPanel2.add(filler1);

            searchBar.setText("127.0.0.1");
            jPanel2.add(searchBar);
            jPanel2.add(filler4);

            connectButton.setText("connect");
            connectButton.setAlignmentX(0.5F);
            connectButton.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
            connectButton.setMaximumSize(new java.awt.Dimension(100, 30));
            connectButton.setPreferredSize(new java.awt.Dimension(100, 30));
            jPanel2.add(connectButton);

            jPanel1.add(jPanel2);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE));
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                              javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE));

            pack();
      }// </editor-fold>//GEN-END:initComponents
      // End of variables declaration//GEN-END:variables
}
